#!/bin/bash

export F_MASTER="/code"
export FC="gfortran"
export FC_EXE="gfortran"
export FC_ENV="gfortran-6-docker"

git clone git@github.com:NCAR/summa.git@sopron_2018
cd summa
make -C build/ -f Makefile
cd ../
mv summa /opt/summa

#EOF
