#!/bin/bash

export F_MASTER="/code"
export FC="gfortran"
export FC_EXE="gfortran"
export FC_ENV="gfortran-6-docker"

git clone --single-branch -b sopron_2018 https://github.com/bartnijssen/summa.git

cd summa
make -C build/ -f Makefile
cd ../
mv summa /opt/summa

#EOF
